
/*
 * This file connects all remaining pieces of AI code together.
 * It shouldn't contain any code itself.
 * 
 * NOTE: order matters!
 * 
 */

var personality;

include(NB_INCLUDES + "math.js.inc");
include(NB_INCLUDES + "intensity.js.inc");
include(NB_INCLUDES + "stats.js.inc");

include(NB_INCLUDES + "adapt.js.inc");
include(NB_INCLUDES + "build.js.inc");
include(NB_INCLUDES + "research.js.inc");
include(NB_INCLUDES + "produce.js.inc");
include(NB_INCLUDES + "group.js.inc");
include(NB_INCLUDES + "tactics.js.inc");
include(NB_INCLUDES + "vtols.js.inc");
include(NB_INCLUDES + "lassat.js.inc");

include(NB_INCLUDES + "timers.js.inc");
include(NB_INCLUDES + "_events.js.inc");
